### ISSUE TITLE
Subgen 404 error

### ISSUE THREAD

**Issue by iammenotyou** [TejasQ/gen-subs#16]
When running subgen for the first time (command: npx subgen models) I receive a 404 error that subgen is not found in the npmjs.

Log:
11 silly logfile done cleaning log files
12 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
13 http fetch GET 404 https://registry.npmjs.org/subgen 448ms (cache skip)
14 http fetch GET 404 https://registry.npmjs.org/subgen 300ms (cache skip)
15 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/subgen - Not found
15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\lib\check-response.js:95:15
15 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
15 verbose stack     at async RegistryFetcher.packument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\registry.js:90:19)
15 verbose stack     at async RegistryFetcher.manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\registry.js:128:23)
15 verbose stack     at async getManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\libnpmexec\lib\index.js:27:22)
15 verbose stack     at async missingFromTree (C:\Program Files\nodejs\node_modules\npm\node_modules\libnpmexec\lib\index.js:60:22)
15 verbose stack     at async C:\Program Files\nodejs\node_modules\npm\node_modules\libnpmexec\lib\index.js:182:32
15 verbose stack     at async Promise.all (index 0)
15 verbose stack     at async exec (C:\Program Files\nodejs\node_modules\npm\node_modules\libnpmexec\lib\index.js:180:3)
15 verbose stack     at async Npm.exec (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:207:9)
16 verbose statusCode 404
17 verbose pkgid subgen@*
18 error code E404
19 error 404 Not Found - GET https://registry.npmjs.org/subgen - Not found
20 error 404
21 error 404  'subgen@*' is not in this registry.
22 error 404
23 error 404 Note that you can also install from a
24 error 404 tarball, folder, http url, or git url.
25 verbose cwd C:\Users\Les\Downloads\gen-subs-main
26 verbose os Windows_NT 10.0.19045
27 verbose node v20.17.0
28 verbose npm  v10.8.2
29 verbose exit 1
30 verbose code 1

**Comment by iceberg53** [comment]
I think that the actual command is `npx gen-subs models` instead of `npx subgen models` .

**Comment by iammenotyou** [comment]
lol, thank you for the very fast response.  I had just realized that (and need more coffee:) and was about the update the post.

**Comment by iammenotyou** [comment]
lol, thank you for the very fast response. I had just realized that (and need more coffee:) and was about the update the post.
