### ISSUE TITLE
changing the highlight color did not work

### ISSUE THREAD

**Issue by horacioh** [TejasQ/gen-subs#3]
I tried to change the highlight color and I got this error at the end of the process:

```
➜  gen-subs npx gen-subs for gen-subs-demo.mp4 -b -f ass -h #0090FF 
? Please choose a model. To download more models, please run `models`. (1.76GB, English) Accurate generic US English model
**✖ hexColor.slice is not a function**
```

Let me know if you need me to test something else. maybe the input was not correct?

**Comment by TejasQ** [comment]
So the issue with this is that `#` in a CLI creates a comment. You effectively sent 

`gen-subs npx gen-subs for gen-subs-demo.mp4 -b -f ass -h `

where `-h` was blank. This is what the error is. I've clarified that in the docs with the above commit. The solution is to wrap it in double quotes. Thank you for testing!
