### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by 3DThangs** [TejasQ/gen-subs#6]
I am new to using github projects. How would I compile this? I installed node.js (NPM and NPX) and ran the `npm gen-subs for [my video]` from the `gen-subs-main` directory and my computer (macOS Monterey) thinks for a moment, and returns:
```
Unknown command: "gen-subs"

Did you mean this?
    npm exec gen-subs # run the "gen-subs" command from either this or a remote npm package

To see a list of supported npm commands, run:
  npm help
```

Any help would be appreciated.

**Comment by TejasQ** [comment]
You've got to run `npx gen-subs`, not `npm gen-subs`. :)
